name: Pull Request Docs Check

on: [pull_request]

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Whether to stop execution of other instances
      max-parallel: 4
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]  #  , "macos-latest"
        python-version: [ "3.8" ]  # "3.7",
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        pip install -r requirements.txt
        pip install -e .
    - name: ONE tests
      run: |
        python -m unittest discover
    # Standard drop-in approach that should work for most people.
    - name: Build docs
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install sphinx-automodapi sphinx_material"
        docs-folder: "docs/"

